# Project-wide Gradle settings.
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.useAndroidX=true
kotlin.code.style=official
android.nonTransitiveRClass=true
org.gradle.configuration-cache=false
android.uniquePackageNames=false
android.dependency.useConstraints=true
android.r8.strictFullModeForKeepRules=false
android.generateSyncIssueWhenLibraryConstraintsAreEnabled=false
android.disallowKotlinSourceSets=false
android.suppressUnsupportedCompileSdk=36

# Poprawka dla b??du INSTALL_BASELINE_PROFILE_FAILED
android.baselineprofile.skipgeneration=true

# Poprawka dla Mockito i Java 25
net.bytebuddy.experimental=true
room.schemaLocation=$projectDir/schemas
